### ISSUE TITLE
CSS work?

### ISSUE THREAD

**Issue by Aaron-Mann** [bulkpinner/site#1]
This is a wonderful web app. However, the interface/stylesheet could definitely be improved. Perhaps Bootstrap could help with this?

**Comment by bulkpinner** [comment]
Hi Aaron-Mann,
Thanks for the feedback!
How do you think it should be improved?
Bootstrap certainly could make it look like a Bootstrap site.

Also please create issuesin the bulkpinner/bulkpinner repository

**Comment by Aaron-Mann** [comment]
I feel like it could do with a bit more asthetic appeal. It doesn't quite fit the Pinterest theme that it is attempting to emulate.  Bootswatch has several free and elegant bootstrap themes. You can visit their site here: https://bootswatch.com

**Comment by bulkpinner** [comment]
Thanks for the suggestion.

I'm very happy with how the site looks. It's simple and functional, and more of a tribute to Pinterest, rather than emulating it as you're suggesting.

Regards,
Luke
